TestTask/Models/ErrorViewModel.cs
namespace TestTask.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestTask/Models/Photo.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace TestTask.Models
{
    public class Photo
    {
        public Photo()
        {
            this.isCopied = false;
        }
        public int Id { get; set; }
        public string Description { get; set; }
        [NotMapped]
        public IFormFile Image { get; set; }
        public string? ImageSrc { get; set; }
        public DateTime uploadTime { get; set; }
        public bool isCopied { get; set; }

        public string getSrc(Photo photo)
        {
            string path = Directory.GetCurrentDirectory() + "/wwwroot/Photos";
            if (!Directory.Exists(path)) { Directory.CreateDirectory(path); }
            string fileName = photo.Image.FileName;
            path = Path.Combine(path, fileName);
            using (var stream = new FileStream(path, FileMode.Create))
            {
                this.Image.CopyTo(stream);
            }
            return fileName;
        }
    }
}

TestTask/Models/isCopiedPhoto.cs
namespace TestTask.Models
{
    public class isCopiedPhoto
    {
        public int Id { get; set; }
        public int photoId { get; set; }
        public string photoDescription { get; set; }
        public byte[] photoData { get; set; }
        public static byte[] GetPhoto(string filePath)
        {
            filePath = Directory.GetCurrentDirectory() + "/wwwroot/Photos/" + filePath;
            FileStream stream = new FileStream(
                filePath, FileMode.Open, FileAccess.Read);
            BinaryReader reader = new BinaryReader(stream);

            byte[] photo = reader.ReadBytes((int)stream.Length);

            reader.Close();
            stream.Close();

            return photo;
        }
    }
}

TestTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TestTask.Models;

namespace TestTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestTask/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestTask.Data;
using TestTask.Models;

namespace TestTask.Controllers
{
    public class PhotosController : Controller
    {
        private readonly AppFirstDBContent _context;
        private readonly AppSecondDBContent _context2;

        public PhotosController(AppFirstDBContent context, AppSecondDBContent context2)
        {
            _context = context;
            _context2 = context2;
        }

        // GET: PhotosController2
        public async Task<IActionResult> Index()
        {
            return _context.Photos != null ?
                        View(await _context.Photos.ToListAsync()) :
                        Problem("Entity set 'AppDBContent.Photos'  is null.");
        }

        // GET: PhotosController2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(p => p.Id == id);
            if (photo == null)
            {
                return NotFound();
            }
            if (!photo.isCopied)
            {
                photo.isCopied = true;
                isCopiedPhoto isCopiedPhoto = new isCopiedPhoto();
                isCopiedPhoto.photoId = photo.Id;
                isCopiedPhoto.photoDescription = photo.Description;
                isCopiedPhoto.photoData = isCopiedPhoto.GetPhoto(photo.ImageSrc);
                _context2.Add(isCopiedPhoto);
                await _context.SaveChangesAsync();
                await _context2.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: PhotosController2/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PhotosController2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description,Image,isCopied")] Photo photo)
        {
            if (ModelState.IsValid)
            {
                photo.uploadTime = DateTime.Now;
                photo.ImageSrc = photo.getSrc(photo);
                _context.Photos.Add(photo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: PhotosController2/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.FindAsync(id);
            if (photo == null)
            {
                return NotFound();
            }
            return View(photo);
        }

        // POST: PhotosController2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ImageSrc,uploadTime,isCopied,Description")] Photo photo)
        {
            _context.Update(photo);
            await _context.SaveChangesAsync();

            //return View(photos);
            return RedirectToAction(nameof(Index));
        }

        // GET: PhotosController2/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Photos == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos
                .FirstOrDefaultAsync(p => p.Id == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: PhotosController2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Photos == null)
            {
                return Problem("Entity set 'AppDBContent.Photos'  is null.");
            }
            var photo = await _context.Photos.FindAsync(id);
            if (photo != null)
            {
                string path = Directory.GetCurrentDirectory() + "/wwwroot/Photos/" + photo.ImageSrc;
                System.IO.File.Delete(path);
                _context.Photos.Remove(photo);
                await _context.SaveChangesAsync();
                if (photo.isCopied)
                {
                    var isCopiedPhoto = await _context2.isCopiedPhotos.Where(c => c.photoId == id).FirstAsync();
                    _context2.isCopiedPhotos.Remove(isCopiedPhoto);
                    await _context2.SaveChangesAsync();
                }

            }
            return RedirectToAction(nameof(Index));
        }
        private bool PhotoExists(int id)
        {
            return (_context.Photos?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TestTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestTask/Views/Photos/Copying.cshtml
@model TestTask.Models.Photo

@{
    ViewData["Title"] = "Сохранение";
}

<h1>Сохранено в secondbase</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desription)
        </dd>
        <img src="@Model.ImageSrc"/>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isCopied)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isCopied)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="GetPhotos">Back to List</a>
</div>

TestTask/Views/Photos/Create.cshtml
@model TestTask.Models.Photo

@{
    ViewData["Title"] = "Добавить фото";
}

<h1>Добавить фото</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-control">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" accept=".jpg,.png,.svg,.ico,.jfif,.jpeg"/>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestTask/Views/Photos/Delete.cshtml
@model TestTask.Models.Photo

@{
    ViewData["Title"] = "Удалить фото";
}

<h1>Удалить</h1>

<h3>Вы точно хотите удалить фото?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Описание
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <img src="~/Photos/@Model.ImageSrc"/>
        <dt class = "col-sm-2">
            Скопированно в secondbase
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isCopied)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Назад к списку</a>
    </form>
</div>

TestTask/Views/Photos/Details.cshtml
@model TestTask.Models.Photo

@{
    ViewData["Title"] = "Копирование в secondbase";
}

<h1>Скопированно в secondbase</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <img src="~/Photos/@Model.ImageSrc"/>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isCopied)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isCopied)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Назад к списку</a>
</div>

TestTask/Views/Photos/Edit.cshtml
@model TestTask.Models.Photo

@{
    ViewData["Title"] = "Редактировать запись";
}

<h1>Редактировать запись</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ImageSrc" />
            <input type="hidden" asp-for="uploadTime" />
            <input type="hidden" asp-for="isCopied" />
            <div class="form-group">
                <label class="control-label">Discription</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <img src="~/Photos/@Model.ImageSrc"/>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад к списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestTask/Views/Photos/GetPhotos.cshtml
@model IEnumerable<TestTask.Models.Photo>
@{
    ViewData["Title"] = "Список фото";
}
<h1>Список фото</h1>

<p>
    <a asp-action="Create">Загрузить фото</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.uploadTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isCopied)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desription)
            </td>
            <td>
                <img src="@item.ImageSrc" class="rounded-circle" width="40" height="40" >
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.uploadTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isCopied)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Copping" asp-route-id="@item.Id">Сохранить в Secondbase</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>

TestTask/Views/Photos/Index.cshtml
@model IEnumerable<TestTask.Models.Photo>

@{
    ViewData["Title"] = "Список всех фото";
}

<h1>Список фото</h1>

<p>
    <a asp-action="Create">Добавить фото</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Описание
            </th>
            <th>
                Фото
            </th>
            <th>
                Время загрузки
            </th>
            <th>
                Скопированно в secondbase
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <img src="~/Photos/@item.ImageSrc" class="rounded-circle" width="100" height="100" >
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.uploadTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isCopied)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Копировать в secondbase</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>

TestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Index">Список записей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Create">Добавить фото</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>